---
title: "Kurs i gjenbruk av kode i R"
number-sections: false
---

Velkommen til kurset i R om gjenbruk av kode med loops, og funksjoner. Kurs inkuldere følgende tema: 

- [Introduksjon til gjenbruk av kode](index.qmd#sec-introduction)
- [Kontroll setninger med if og else](kontroll.qmd)
- [For- og whileløkker](loops.qmd)
- [Hvordan skrive funksjoner](funksjoner.qmd)


## Introduksjon til gjenbruk av kode {#sec-introduction}
Gjenbruk er et av [åtte grunnleggende IT-arkitekturprinsipper vi bruker i SSB](https://statistics-norway.atlassian.net/wiki/spaces/Arkitektur/pages/3538714625). Gjenbruk gjør at man slipper å kode det samme som noen allerede har gjort, og er lurt med tanke på kostnadseffektivitet, vedlikehold og sikkerhet.

Det er 4 type gjenbruk som vi bruke i SSB. Dette kurset fokusere på det første:

-   [**Gjenbruk i egen kode**](index.qmd#sec-gjenbruk): Gjenbruk i egen kode vil si å skille ut duplisert kode til loops eller egne funksjoner.
-   **Gjenbruk ved kopiering**: Dette er gjenbruk ved klipp og lim fra annen kode, enten ekstern (stack overflow, google, ChatGPT etc) eller intern.
-   **Gjenbruk av biblioteker**: Dette er gjenbruk ved klipp og lim fra annen kode, enten ekstern (stack overflow, google, ChatGPT etc) eller intern.
-   **Fellestjenester**: Fellestjenester er felles behov som ikke kan løses av bibliotek alene. Dette omfatter blant annet plattformtjenester, mikrotjenester og GUI-baserte tjenester. Her er det snakk om interne tjenester som utvikles av SSB.

## Gjenbruk i egen kode {#sec-gjenbruk}

Fordeler inkludere:

-   Unngår duplisering, dvs. retting og forbedring ett sted i stedet for flere steder.
-   Mindre kompleksitet og mer lesbart.
-   Lettere å teste og refaktorere (endre kode til bedre struktur uten å endre funksjonalitet)
-   Bidrar til å generalisere koden, noe som letter gjenbruk.

Ulemper:

-   Må utvikle og vedlikeholde koden selv.
-   Unødvendig hvis det allerede finnes en funksjon i et bibliotek som gjør det samme.
-   Kompetanseterskel

Se [**Beste praksis for gjenbruk av kode i SSB**](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3527966755/Gjenbruk) for mer detaljer og anbefalinger.